{% set name = "seqlike" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seqlike-{{ version }}.tar.gz
  sha256: 0a39067ee3ba97465aad5491b5f7aa15f67182c13ef168d00e703be01cc28dd4

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - requests
    - lazy_loader
  run:
    - python >=3.6
    - biopython
    - multipledispatch
    - numpy
    - pandas
    - pillow
    - pytest
    - pytest-regtest
    - python-codon-tables
    - scikit-learn
    - weblogo
    # See notes on lazy_loader
    # - https://github.com/conda-forge/seqlike-feedstock/pull/7#issuecomment-1140347680
    # - https://github.com/conda-forge/seqlike-feedstock/pull/7#issuecomment-1146537036
    - lazy_loader
    # suggested by auto-tick bot
    - requests

test:
  imports:
    - seqlike
    - seqlike.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/modernatx/seqlike
  summary: 'SeqLike: Flexible Biological Sequence Objects in Python'
  license: Apache-2.0
  license_file: LICENSE
  description: |
    SeqLike is a Python package that lets you conveniently manipulate 
    biological sequences.
    It solves some of the following problems:

    1. Sequence representation inter-conversion (AA vs. NT, and 
       str/Seq/SeqRecord/arrays) via a single object's API.
    2. Processing a collection of sequences easily in Python without 
       needing to switch out to a shell.
    3. Convenience APIs to visualize of a collection of sequences.

    PyPI: [https://pypi.org/project/seqlike/](https://pypi.org/project/seqlike/)

  doc_url: https://modernatx.github.io/seqlike/
  dev_url: https://github.com/modernatx/seqlike

extra:
  recipe-maintainers:
    - sugatoray
    - ericmjl
    ## Maintainers from bioconda
    - raivivek

## NOTE: >> DO NOT REMOVE THIS NOTE TO AVOID PLAUSIBLE CONFUSION IN FUTURE
#
#  SUMMARY: The three recipes (seqlike, weblogo, python-codon-tables) 
#           were managed by bioconda channel. Since the creators of 
#           seqlike wanted it on conda-forge, we ported all three 
#           libraries from bioconda channel to conda-forge channel, 
#           with permission from bioconda-core-team. The other two 
#           libraries (weblogo, python-codon-tables) are dependencies 
#           of `seqlike`.
#
#  TODO: 
#         1. Remind bioconda team to remove "seqlike" from 
#            bioconda channel, to complete the transfer of 
#            "seqlike" from bioconda to conda-forge. [DONE]
#
#         2. Ask the maintainers of bioconda:seqlike whether 
#            to add them to the maintainers' list here. [DONE]
#
#  See: 
#    - Comment: 
#      https://github.com/conda-forge/staged-recipes/pull/17283#issuecomment-1001016875
#      By: dpryan79 (from bioconda team)
#    - For more information see this:
#      https://github.com/conda-forge/staged-recipes/pull/17283#issuecomment-1000523651
#      
##-------------------------------------------------------------------------
